import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _translations = {
    'en': {
      'app_name': 'DeenSphere',
      'home': 'Home',
      'qa': 'Q&A',
      'quran': 'Quran',
      'prayer': 'Prayer',
      'settings': 'Settings',
      'profile': 'Profile',
      'bookmarks': 'Bookmarks',
      'logout': 'Logout',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'appearance': 'Appearance',
      'support': 'Support',
      'share_app': 'Share App',
      'edit_profile': 'Edit Profile',
      'my_orders': 'My Orders',
      'featured_tools': 'Featured Tools',
      'explore': 'Explore',
      'global_news': 'Global News',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'welcome': 'Welcome',
      'next_prayer': 'Next Prayer',
      'good_night': 'Good Night',
    },
    'ar': {
      'app_name': 'دين سفير',
      'home': 'الرئيسية',
      'qa': 'سؤال وجواب',
      'quran': 'القرآن',
      'prayer': 'الصلاة',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'bookmarks': 'الإشارات المرجعية',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'dark_mode': 'الوضع الداكن',
      'notifications': 'التنبيهات',
      'appearance': 'المظهر',
      'support': 'الدعم',
      'share_app': 'مشاركة التطبيق',
      'edit_profile': 'تعديل الملف الشخصي',
      'my_orders': 'طلباتي',
      'featured_tools': 'أدوات مميزة',
      'explore': 'استكشاف',
      'global_news': 'الأخبار العالمية',
      'good_morning': 'صباح الخير',
      'good_afternoon': 'مساء الخير',
      'good_evening': 'مساء الخير',
      'welcome': 'مرحباً',
      'next_prayer': 'الصلاة القادمة',
      'good_night': 'تصبح على خير',
    },
    'ur': {
      'app_name': 'دین سفیر',
      'home': 'ہوم',
      'qa': 'سوال و جواب',
      'quran': 'قرآن',
      'prayer': 'نماز',
      'settings': 'ترتیبات',
      'profile': 'پروفائل',
      'bookmarks': 'بک مارکس',
      'logout': 'لاگ آؤٹ',
      'language': 'زبان',
      'dark_mode': 'ڈارک موڈ',
      'notifications': 'اطلاعات',
      'appearance': 'ظاہری شکل',
      'support': 'سپورٹ',
      'share_app': 'ایپ شیئر کریں',
      'edit_profile': 'پروفائل میں ترمیم کریں',
      'my_orders': 'میرے آرڈرز',
      'featured_tools': 'نمایاں ٹولز',
      'explore': 'تلاش کریں',
      'global_news': 'عالمی خبریں',
      'good_morning': 'صبح بخیر',
      'good_afternoon': 'دوپہر بخیر',
      'good_evening': 'شام بخیر',
      'welcome': 'خوش آمدید',
      'next_prayer': 'اگلی نماز',
      'good_night': 'شب بخیر',
    },
    'tr': {
      'app_name': 'DeenSphere',
      'home': 'Anasayfa',
      'qa': 'Soru-Cevap',
      'quran': 'Kuran',
      'prayer': 'Namaz',
      'settings': 'Ayarlar',
      'profile': 'Profil',
      'bookmarks': 'Yer İmleri',
      'logout': 'Çıkış Yap',
      'language': 'Dil',
      'dark_mode': 'Karanlık Mod',
      'notifications': 'Bildirimler',
      'appearance': 'Görünüm',
      'support': 'Destek',
      'share_app': 'Uygulamayı Paylaş',
      'edit_profile': 'Profili Düzenle',
      'my_orders': 'Siparişlerim',
      'featured_tools': 'Öne Çıkan Araçlar',
      'explore': 'Keşfet',
      'global_news': 'Küresel Haberler',
      'good_morning': 'Günaydın',
      'good_afternoon': 'Tünaydın',
      'good_evening': 'İyi Akşamlar',
      'welcome': 'Hoş Geldiniz',
      'next_prayer': 'Sıradaki Namaz',
      'good_night': 'İyi Geceler',
    },
    'id': {
      'app_name': 'DeenSphere',
      'home': 'Beranda',
      'qa': 'Tanya Jawab',
      'quran': 'Quran',
      'prayer': 'Shalat',
      'settings': 'Pengaturan',
      'profile': 'Profil',
      'bookmarks': 'Bookmark',
      'logout': 'Keluar',
      'language': 'Bahasa',
      'dark_mode': 'Mode Gelap',
      'notifications': 'Notifikasi',
      'appearance': 'Tampilan',
      'support': 'Dukungan',
      'share_app': 'Bagikan Aplikasi',
      'edit_profile': 'Ubah Profil',
      'my_orders': 'Pesanan Saya',
      'featured_tools': 'Alat Unggulan',
      'explore': 'Jelajah',
      'global_news': 'Berita Global',
      'good_morning': 'Selamat Pagi',
      'good_afternoon': 'Selamat Siang',
      'good_evening': 'Selamat Sore',
      'welcome': 'Selamat Datang',
      'next_prayer': 'Shalat Berikutnya',
      'good_night': 'Selamat Malam',
    },
    'fr': {
      'app_name': 'DeenSphere',
      'home': 'Accueil',
      'qa': 'Q&R',
      'quran': 'Coran',
      'prayer': 'Prière',
      'settings': 'Paramètres',
      'profile': 'Profil',
      'bookmarks': 'Signets',
      'logout': 'Déconnexion',
      'language': 'Langue',
      'dark_mode': 'Mode Sombre',
      'notifications': 'Notifications',
      'appearance': 'Apparence',
      'support': 'Support',
      'share_app': 'Partager l\'application',
      'edit_profile': 'Modifier le profil',
      'my_orders': 'Mes commandes',
      'featured_tools': 'Outils en vedette',
      'explore': 'Explorer',
      'global_news': 'Actualités mondiales',
      'good_morning': 'Bon matin',
      'good_afternoon': 'Bon après-midi',
      'good_evening': 'Bonsoir',
      'welcome': 'Bienvenue',
      'next_prayer': 'Prochaine prière',
      'good_night': 'Bonne nuit',
    },
    'es': {
      'app_name': 'DeenSphere',
      'home': 'Inicio',
      'qa': 'P&R',
      'quran': 'Corán',
      'prayer': 'Oración',
      'settings': 'Ajustes',
      'profile': 'Perfil',
      'bookmarks': 'Marcadores',
      'logout': 'Cerrar sesión',
      'language': 'Idioma',
      'dark_mode': 'Modo oscuro',
      'notifications': 'Notificaciones',
      'appearance': 'Apariencia',
      'support': 'Soporte',
      'share_app': 'Compartir aplicación',
      'edit_profile': 'Editar perfil',
      'my_orders': 'Mis pedidos',
      'featured_tools': 'Herramientas destacadas',
      'explore': 'Explorar',
      'global_news': 'Noticias globales',
      'good_morning': 'Buenos días',
      'good_afternoon': 'Buenas tardes',
      'good_evening': 'Buenas noches',
      'welcome': 'Bienvenido',
      'next_prayer': 'Próxima oración',
      'good_night': 'Buenas noches',
    },
    'bn': {
      'app_name': 'দ্বীনস্ফিয়ার',
      'home': 'হোম',
      'qa': 'প্রশ্ন ও উত্তর',
      'quran': 'কুরআন',
      'prayer': 'নামাজ',
      'settings': 'সেটিংস',
      'profile': 'প্রোফাইল',
      'bookmarks': 'বুকমার্ক',
      'logout': 'লগআউট',
      'language': 'ভাষা',
      'dark_mode': 'ডার্ক মোড',
      'notifications': 'নোটিফিকেশন',
      'appearance': 'চেহারা',
      'support': 'সাপোর্ট',
      'share_app': 'অ্যাপ শেয়ার করুন',
      'edit_profile': 'প্রোফাইল এডিট করুন',
      'my_orders': 'আমার অর্ডার',
      'featured_tools': 'নির্বাচিত সরঞ্জাম',
      'explore': 'অন্বেষণ করুন',
      'global_news': 'বিশ্ব সংবাদ',
      'good_morning': 'শুভ সকাল',
      'good_afternoon': 'শুভ দুপুর',
      'good_evening': 'শুভ সন্ধ্যা',
      'welcome': 'স্বাগতম',
      'next_prayer': 'পরবর্তী নামাজ',
      'good_night': 'শুভ রাত্রি',
    },
    'hi': {
      'app_name': 'दीनस्फीयर',
      'home': 'होम',
      'qa': 'सवाल-जवाब',
      'quran': 'कुरान',
      'prayer': 'नमाज़',
      'settings': 'सेटिंग्स',
      'profile': 'प्रोफ़ाइल',
      'bookmarks': 'बुकमार्क',
      'logout': 'लॉगआउट',
      'language': 'भाषा',
      'dark_mode': 'डार्क मोड',
      'notifications': 'नोटिफिकेशन',
      'appearance': 'दिखावट',
      'support': 'सपोर्ट',
      'share_app': 'ऐप शेयर करें',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'my_orders': 'मेरे आदेश',
      'featured_tools': 'प्रमुख उपकरण',
      'explore': 'एक्सप्लोर करें',
      'global_news': 'वैश्विक समाचार',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'नमस्कार',
      'good_evening': 'शुभ संध्या',
      'welcome': 'स्वागत है',
      'next_prayer': 'अगली नमाज़',
      'good_night': 'शुभ रात्रि',
    },
    'ru': {
      'app_name': 'DeenSphere',
      'home': 'Главная',
      'qa': 'Вопросы и ответы',
      'quran': 'Коран',
      'prayer': 'Молитва',
      'settings': 'Настройки',
      'profile': 'Профиль',
      'bookmarks': 'Закладки',
      'logout': 'Выйти',
      'language': 'Язык',
      'dark_mode': 'Темный режим',
      'notifications': 'Уведомления',
      'appearance': 'Внешний вид',
      'support': 'Поддержка',
      'share_app': 'Поделиться приложением',
      'edit_profile': 'Редактировать профиль',
      'my_orders': 'Мои заказы',
      'featured_tools': 'Популярные инструменты',
      'explore': 'Исследовать',
      'global_news': 'Мировые новости',
      'good_morning': 'Доброе утро',
      'good_afternoon': 'Добрый день',
      'good_evening': 'Добрый вечер',
      'welcome': 'Добро пожаловать',
      'next_prayer': 'Следующая молитва',
      'good_night': 'Спокойной ночи',
    },
  };

  String translate(String key) {
    return _translations[locale.languageCode]?[key] ??
        _translations['en']![key]!;
  }

  static const Delegate delegate = Delegate();
}

class Delegate extends LocalizationsDelegate<AppLocalizations> {
  const Delegate();

  @override
  bool isSupported(Locale locale) => [
    'en',
    'ar',
    'ur',
    'tr',
    'id',
    'fr',
    'es',
    'bn',
    'hi',
    'ru',
  ].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(Delegate old) => false;
}
